#!/bin/bash
# ─────────────────────────────────────────────────
# Forex Trading Bot — Environment Setup
# Creates forex-bot.env in the project directory with all required secrets
# Run this once on any new server before starting the bot.
# ─────────────────────────────────────────────────

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

ENV_FILE="/home/vanhansen53/forex_trading_bot/forex-bot.env"

echo ""
echo "════════════════════════════════════════════════════════"
echo -e "${YELLOW}  JARVIS BOT — Environment Setup${NC}"
echo "════════════════════════════════════════════════════════"
echo ""

# Check if file already exists
if [ -f "$ENV_FILE" ]; then
    echo -e "${YELLOW}⚠  $ENV_FILE already exists.${NC}"
    echo ""
    cat "$ENV_FILE" | grep -v '^#' | grep '=' | while IFS='=' read -r key value; do
        # Mask the values for display
        masked="${value:0:4}****"
        echo "    $key=$masked"
    done
    echo ""
    read -p "  Overwrite? (y/N): " OVERWRITE
    if [[ "$OVERWRITE" != "y" && "$OVERWRITE" != "Y" ]]; then
        echo "  Keeping existing file."
        exit 0
    fi
fi

echo -e "${YELLOW}Setting up environment variables...${NC}"
echo ""

# 1. WEBHOOK_SECRET — auto-generate
WEBHOOK_SECRET=$(python3 -c "import secrets; print(secrets.token_urlsafe(32))" 2>/dev/null)
if [ -z "$WEBHOOK_SECRET" ]; then
    WEBHOOK_SECRET=$(openssl rand -base64 32 2>/dev/null | tr -d '/+=' | head -c 43)
fi
echo -e "  ${GREEN}✓${NC} WEBHOOK_SECRET auto-generated"

# 2. Telegram Bot Token
echo ""
echo "  Get your bot token from @BotFather on Telegram."
read -p "  TELEGRAM_BOT_TOKEN: " TELEGRAM_BOT_TOKEN

if [ -n "$TELEGRAM_BOT_TOKEN" ]; then
    # Validate token by calling getMe
    RESULT=$(python3 -c "
import urllib.request, json
try:
    r = urllib.request.urlopen('https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/getMe', timeout=10)
    d = json.loads(r.read())
    if d.get('ok'):
        print(d['result']['username'])
    else:
        print('INVALID')
except:
    print('INVALID')
" 2>/dev/null)

    if [ "$RESULT" = "INVALID" ] || [ -z "$RESULT" ]; then
        echo -e "  ${RED}✗ Token invalid or unreachable. Saving anyway — fix later.${NC}"
    else
        echo -e "  ${GREEN}✓${NC} Verified: @${RESULT}"
    fi
fi

# 3. Telegram Chat ID
echo ""
echo "  Your personal chat ID (send /start to @userinfobot to find it)."
read -p "  TELEGRAM_CHAT_ID: " TELEGRAM_CHAT_ID

# 4. Telegram Group ID
echo ""
echo "  Group chat ID (optional, add bot to group then check with @userinfobot)."
read -p "  TELEGRAM_GROUP_ID (or press Enter to skip): " TELEGRAM_GROUP_ID

# Write the file
echo ""
echo -e "${YELLOW}Writing $ENV_FILE ...${NC}"

cat > "$ENV_FILE" << ENVEOF
# Forex Trading Bot — Environment Configuration
# Generated by setup_env.sh on $(date)
# DO NOT commit this file. It is gitignored.

# Webhook security
WEBHOOK_SECRET=${WEBHOOK_SECRET}

# Telegram Bot (@Jarvis_kkbot)
TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
TELEGRAM_GROUP_ID=${TELEGRAM_GROUP_ID}
ENVEOF

chmod 600 "$ENV_FILE"
sudo chown "$(whoami)" "$ENV_FILE"


echo ""
echo "════════════════════════════════════════════════════════"
echo -e "${GREEN}  ✅ Environment configured${NC}"
echo "════════════════════════════════════════════════════════"
echo ""
echo "  File:        $ENV_FILE"
echo "  Permissions: 600 (owner-only)"
echo ""
echo "  Next steps:"
echo "    bash restart_bot.sh      # Start the bot"
echo "    bash stop_bot.sh         # Stop the bot"
echo ""
