#!/bin/bash
# Setup Telegram Bot for Forex Trading Alerts
# Follow these steps to create your bot

echo "========================================"
echo "TELEGRAM BOT SETUP FOR TRADING ALERTS"
echo "========================================"
echo ""
echo "STEP 1: Create a new bot with BotFather"
echo "----------------------------------------"
echo "1. Open Telegram and search for @BotFather"
echo "2. Start a chat and send: /newbot"
echo "3. Choose a name for your bot (e.g., 'My Forex Alerts')"
echo "4. Choose a username ending in 'bot' (e.g., 'myforexalerts_bot')"
echo "5. BotFather will give you a TOKEN like:"
echo "   1234567890:ABCdefGHIjklMNOpqrSTUvwxYZ123456789"
echo ""
echo "STEP 2: Get your Chat ID"
echo "-------------------------"
echo "1. Start a chat with your new bot (search for it by username)"
echo "2. Send any message to the bot"
echo "3. Visit this URL in your browser (replace YOUR_TOKEN):"
echo "   https://api.telegram.org/botYOUR_TOKEN/getUpdates"
echo "4. Look for 'chat':{'id':XXXXXXX} - that number is your Chat ID"
echo ""
echo "STEP 3: Configure the bot"
echo "--------------------------"
echo "Run these commands with your actual values:"
echo ""
echo "  export TELEGRAM_BOT_TOKEN='your_bot_token_here'"
echo "  export TELEGRAM_CHAT_ID='your_chat_id_here'"
echo ""
echo "Or add to ~/.bashrc for persistence:"
echo "  echo \"export TELEGRAM_BOT_TOKEN='your_token'\" >> ~/.bashrc"
echo "  echo \"export TELEGRAM_CHAT_ID='your_chat_id'\" >> ~/.bashrc"
echo "  source ~/.bashrc"
echo ""
echo "STEP 4: Test the connection"
echo "----------------------------"
echo "Run: python3 scripts/test_telegram.py"
echo ""
echo "========================================"
